[package]
name = "parser"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
binary_rw = "2.0.2"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
num_enum = "0.5.7"